sudo: false

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - secure: "Oz9s8Yq+briRgqh64XPnkSWFYZEUAVUIHyybVPLigjp0yaqy317aZ/gkL4SwYRBrVEjih1sWBkxy0QAmVk7wrAJHhTrPcZN3mLPm8Wkzn6t9LOu0XzNFj86XTUjCVnW9TgUqsd3ODhNDwSRDCtU7c6NqBgv+FbpTYQVw8iggJR7c+0SUmUOQpGB8DyFlotyewm9tamkH9RNebO6xtmHYxsDK2Hn5o6Y3DxgJYCWO65auiG7u8JHnpykmPh/97estKROpXjmz8u5d6V6aBJ/mSrrjc5J66+BMhpicTSVlYfDetxDYH+5AJxkPtgYjZkYn/dhHehlvuhUuYZWIjqVa/6/WT2OTRM3y80QyLLcW6hV8NX8Exx35GT6ctidlRFm7psPhVAeE1Uvs+qdXge+uauzg0l1zKRuKtr3sAYNfM1+QqnaiT6vAjZox37Tqp6LHTwpWFUIFgY0O1ddN2hpzu2L1GDgZAO6/DjKfiCdPl1NGEmMoNBjpaUzdlzSKQLyEWugx+ngJ3VFNLcamZNlN+1iqICaCYHTr+5CIyLwp6ZiSDwH6Rs/815P0Knwxj9T7DqXYwUbwlEPk89kSgBsVue0rH6SQ6JOHwDD9xzodRgS33nuD4yOYWwsqb0qwsZxzJsHm4iaD0RlgjMSMfjQtdv2q0psw6Vubqkj7yHR7adI="
    - secure: "ZnF41aVZcARQbKBzejoBD6p8DCTKAAQQwdJ1mQqXCoLu/vhTWhwph1pO5447poZTiUZ01Xc+8cePm4IYocu3UqtvoZIGIUBJRefmEZLDJwbJSXICG9E9YMFgWy2C3ZfrFisjj8XjcFyAcO9Y+Zd+FhwZipU5o/HtveL5jNeuBXMmsQ54ukFqfjYGNWEoakqgUFwN1sAAR2rhKHT6LTNl9Dr7cAbUePrwlZL1bA5K/btDJu7qOxiDrbvF8g1QZ3XlkyBahfZ/KWtYS1HnBpXxMfd1h4cfIKSB2fsTZiBAMVk3hlxl8M9FBnTY6BHjql2GNFcREq4QrcJ5/hNMfduVX+6143SgtFRoHddo7XNod1oc1VS/hMheDRrMctci8+cog1uN2996yEUwWSDaZ8wq0DM3YIKPjYtm5RkQaTc8/9FCJf2ki/Lc4C0d8A95Gl31BGp556sLEwyT1aDCX2YVlMz922a8xaSeGABxbJU+MqRVB5KPTnxpW8YyLcELE9eGwOqlQiKYBmVzhjzKd3yLq9RFeUx0pVGrz7sp2/p07jLenB7XmX1fFC11wFng0mCKsBV0pndVF3pEKtu5WqONZ5xarjEUU9fAna6API8EddOJT0Dh6EVq0FPLwGOGQf5fvbFn6rhv8q1/s0y0umi7RGB1n03vDkq8uMBZUDNsFbc="
    - secure: "a61oow2CGqHSGglb6OxMJPYevqvvjaWENvdfeiwXno7WrHbq7xpsZTB+KuwUfXj0zdBtxxp3ji5DAenS6TWQ8fv0PvhXhIZJLot999i91o96K+2yg8dTOWXOG6/jNy2DmKk39S+Iq1fsvPRPoELj4ETxOyxqSio2ooMDRrUWEfpriff6uuYIGbnc5o0aBjseFSiebvocd1BMsdRrimeqty/Iky8n5taVjRIhjNNt2mT6d91OlVfmjbSyyzZW9HCX//EV8cZtngrkVRyO+U3Z/kbX4KJU6ZO5CIEt1JNq2Fpv6/9a1J6UBbUsWZbRalCbEhKy4yciHQZDxuUTWlHcafjimvHiHioosu9an7IRyZ0YCTmgpZGo0oCDpfW/AAMfLs/7PkpeSeJQZ0227crDqcDtidFivyEzFuX/EqN+VbWn7mYH+0whlCO5CpRvKGKzwGSwuXs8ymhg8upNearudfhr3pUvRjhPucfSflyyUXh4cjXD+dlTivAyIVDC5BJpcb3l37jYLgk7Y1UklflyjUkkSMWe22dYZKFIMyqqnytTT4jIQufZ5mqURNr9AjxHQ6qhl6Bvu/24LtQ5iX8ZYI3TjwsC3ACqVmkoeivCq3iQB28iUYGoHJROddWOM2E55ZZwIrQPNkIBx+AoHK1uRvyKXfPs+zEDa9ICeZ33Lbs="


install:
  - mvn --version
  - mvn -B install -U -DskipTests=true -Dgpg.skip=true

script:
  - mvn -B verify -U -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - util/deploy.sh

# To deploy the site is required Maven 3.3.x:
# https://cwiki.apache.org/confluence/display/MAVEN/AetherClassNotFound
# https://github.com/github/maven-plugins/issues/46
#after_success:
  #- util/deploy-site.sh
